accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('login/', views.UserLoginView.as_view(), name='user-login'),
    path('logout/', views.UserLogoutView.as_view(), name='user-logout'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='user-profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset-password'),
    path('reset/done/', views.UserPasswordResetDone.as_view(), name='password-reset-done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('confirm/confirm/', views.UserPasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('follow/<int:pk>/', views.UserFollowView.as_view(), name='user-follow'),
    path('unfollow/<int:pk>/', views.UserUnFollowView.as_view(), name='user-unfollow'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'


urlpatterns = [

    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:pk>/<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/delete/<int:pk>/', views.PostDeleteView.as_view(), name='post-delete'),
    path('post/update/<int:pk>/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/create/', views.PostCreateView.as_view(), name='post-create'),
    path('reply/<int:post_pk>/<int:commet_pk>/', views.PostAddReplyView.as_view(), name='add-reply'),
    path('like/<int:pk>/', views.PostLikeView.as_view(), name='post-like'),

]

home/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()
    slug = models.SlugField(unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('home:post-detail', args=[self.id, self.slug])

    def like_count(self):
        return self.pvotes.count()

    def user_can_like(self, user):
        user_likes = user.uvotes.all().filter(post=self)
        if user_likes.exists():
            return True
        return False


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments', null=True, blank=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} ----> {self.body[:30]}'


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvotes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvotes')

    def __str__(self):
        return f'{self.user} ----> {self.post.slug}'

home/forms.py
from django import forms
from .models import Post, Comment


class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['body', ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 4, 'placeholder': 'لطفاً نظرتان را در اینجا بنویسید'}),
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body', ]
        widgets = {
            'body': forms.Textarea(attrs={
                'placeholder': 'Enter your comment here...',
                'rows': 2,
                'class': 'form-control'
            }),
        }


class PostSearchForm(forms.Form):
    search = forms.CharField()

home/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator
# from django.utils.text import slugify
from slugify import slugify
from django.views import View

from .models import Post, Comment, Vote
from .forms import PostCreateUpdateForm, CommentForm, CommentReplyForm, PostSearchForm


class HomeView(View):
    form_class = PostSearchForm

    def get(self, request):
        posts = Post.objects.all()

        if request.GET.get('search'):
            posts = posts.filter(body__icontains=request.GET['search'])

        return render(request, 'home/index.html', {'posts': posts, 'form': self.form_class})


class PostDetailView(View):
    form_class = CommentForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(
            Post, pk=kwargs['pk'], slug=kwargs['slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, pk, slug):
        can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like = True

        comments = self.post_instance.pcomments.filter(is_reply=False)
        return render(request, 'home/detail.html',
                      {'post': self.post_instance, 'comments': comments, 'form': self.form_class,
                       'reply_form': self.form_class_reply, 'can_like': can_like})

    @method_decorator(login_required)
    def post(self, request, pk, slug):
        form = self.form_class(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = self.post_instance
            comment.user = request.user
            comment.save()
            messages.success(
                request, 'نظر شما با موفقیت ذخیره شد', extra_tags='success')
            return redirect('home:post-detail', pk=self.post_instance.pk, slug=self.post_instance.slug)
        else:
            comments = self.post_instance.pcomments.filter(is_reply=False)
            messages.warning(
                request, '.لطفا درست و حسابی فرم رو پر کن', extra_tags='warning')
        return render(request, 'home/detail.html', {'post': self.post_instance, 'form': form, 'comments': comments})


class PostDeleteView(LoginRequiredMixin, View):

    def dispatch(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs['pk'])

        if not post.user.id == request.user.id:
            messages.error(
                request, 'شما اجازه حذف این پست رو ندارید', extra_tags='danger')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        return render(request, 'home/post_confirm_delete.html', {'post': post})

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        post.delete()
        messages.success(request, 'پست شما با موفقیت حذف شد',
                         extra_tags='success')
        return redirect('home:home')


class PostUpdateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['pk'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(
                request, 'شما اجازه بروزرسانی پست رو ندارید', extra_tags='danger')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, 'home/update.html', {'post': post, 'form': form})

    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()

            messages.success(
                request, 'اطلاعات پست با موفقیت تغییر کرد', extra_tags='success')
            return redirect('home:post-detail', post.id, post.slug)
        return render(request, 'home/update.html', {'form': form})


class PostCreateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, 'home/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(
                request, 'پست شما با موفقیت ذخیره شد', extra_tags='success')
            return redirect('home:post-detail', new_post.id, new_post.slug)

        return render(request, 'home/create.html', {'form': form})


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_pk, commet_pk):
        post = get_object_or_404(Post, pk=post_pk)
        comment = get_object_or_404(Comment, pk=commet_pk)
        form = self.form_class(request.POST)

        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(
                request, 'نظر شما با موفقیت ثبت شد', extra_tags='success')
        return redirect('home:post-detail', post.pk, post.slug)


class PostLikeView(LoginRequiredMixin, View):

    # def dispatch(self, request, *args, **kwargs):
    #     post = get_object_or_404(Post, pk=kwargs['pk'])
    #     vote = Vote.objects.filter(post=post, user=request.user)
    #
    #     if vote.exists():
    #         if vote.first().user == request.user:
    #             messages.error(request, 'شما قبلاً این پست را لایک کرده‌اید', extra_tags='danger')
    #             return redirect('home:home')
    #
    #     return super().dispatch(request, *args, **kwargs)

    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        like = Vote.objects.filter(post=post, user=request.user)

        if like.exists():
            messages.error(request, 'شما این پست رو قبلا لایک کردید', extra_tags='danger')
        else:
            Vote.objects.create(post=post, user=request.user)
            messages.success(request, 'شما این پست رو لایک کردید', extra_tags='success')
        return redirect('home:post-detail', post.pk, post.slug)

home/templates/home/create.html
{% extends '_base.html' %}


{% block page_title %}
    Create
{% endblock %}


{% block content %}


    <form action="" method="post" novalidate>


        {% csrf_token %}
        {{ form.as_p }}


        <input type="submit" class="btn btn-info" value="Create">


    </form>


{% endblock %}

home/templates/home/detail.html
{% extends '_base.html' %}

{% block page_title %}
    Detail
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">
                <a href="{% url 'accounts:user-profile' post.user.pk %}"
                   class="text-decoration-none">{{ post.user.username }}</a>
                - {{ post.updated|date:"Y-M" }}
            </div>
            <div class="card-body">
                <p>{{ post.body }}</p>
            </div>
            {% if request.user.id == post.user.id %}
                <div class="card-footer">
                    <a href="{% url 'home:post-delete' post.pk %}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'home:post-update' post.pk %}" class="btn btn-info">Update</a>
                </div>
            {% endif %}
        </div>
        <hr>

        {% if request.user.is_authenticated %}
            <div class="mb-3">
                <a href="{% url 'home:post-like' post.pk %}" class="{% if can_like %}disabled{% endif %} btn btn-dark">
                    <i class="fas fa-heart"></i> Like <span class="badge badge-light">{{ post.like_count }}</span>
                </a>
            </div>
        {% endif %}

        <h4>{{ comments.count }} Comments</h4>
        {% for comment in comments %}
            <div class="card mt-3">
                <div class="card-header">
                    {{ comment.user }} | {{ comment.created|timesince }}
                </div>
                <div class="card-body">
                    <p>{{ comment.body }}</p>
                </div>

                <!-- Replies Section -->
                {% with replies=comment.rcomments.all %}
                    <div class="card-footer">
                        {% for reply in replies %}
                            <div class="bg-light p-2 mt-2">
                                <p class="text-muted">{{ reply.user }}</p>
                                <p>{{ reply.body }}</p>
                            </div>
                        {% endfor %}

                        <!-- Reply Form -->
                        {% if request.user.is_authenticated %}
                            <div class="mt-3">
                                <form action="{% url 'home:add-reply' post.pk  comment.pk %}" method="post">
                                    {% csrf_token %}
                                    {{ reply_form.as_p }}
                                    <button type="submit" class="btn btn-sm btn-primary mt-2">Send Reply</button>
                                </form>
                            </div>
                        {% endif %}
                    </div>
                {% endwith %}
            </div>
        {% empty %}
            <p class="text-muted mt-3">No Comments yet.</p>
        {% endfor %}
    </div>

    <hr>

    {% if request.user.is_authenticated %}
        <div class="container mt-4">
            <form action="" method="post" novalidate class="needs-validation">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">ارسال</button>
            </form>
        </div>
    {% endif %}
{% endblock %}

home/templates/home/index.html
{% extends "_base.html" %}



{% block page_title %}


    StackOverFlow

{% endblock page_title %}




{% block content %}


    <form action="" method="get">

        {{ form.as_p }}

        <input type="submit" class="btn btn-dark" value="Search">


    </form>

    <br>
    <br>

    <div class="card">

        {% for post in posts %}

            <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.body|truncatechars:15 }}</a>

        {% endfor %}


    </div>




{% endblock content %}

home/templates/home/post_confirm_delete.html
{% extends '_base.html' %}

{% block page_title %}
    حذف پست
{% endblock %}

{% block content %}
<div class="container mt-5" dir="rtl">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-danger text-white">
                    <h2>حذف پست</h2>
                </div>
                <div class="card-body">
                    <p>آیا مطمئن هستید که می‌خواهید پست با عنوان "<strong>{{ post.slug }}</strong>" را حذف کنید؟</p>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="submit" value="تأیید" class="btn btn-danger">
                            <a href="{% url 'home:home' %}" class="btn btn-secondary">انصراف</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/update.html
{% extends '_base.html' %}


{% block page_title %}
    Update
{% endblock %}


{% block content %}


    <form action="" method="post" novalidate>


        {% csrf_token %}
        {{ form.as_p }}


        <input type="submit" class="btn btn-info" value="Update">


    </form>


{% endblock %}