accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('login/', views.UserLoginView.as_view(), name='user-login'),
    path('logout/', views.UserLogoutView.as_view(), name='user-logout'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='user-profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset-password'),
    path('reset/done/', views.UserPasswordResetDone.as_view(), name='password-reset-done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('confirm/confirm/', views.UserPasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('follow/<int:pk>/', views.UserFollowView.as_view(), name='user-follow'),
    path('unfollow/<int:pk>/', views.UserUnFollowView.as_view(), name='user-unfollow'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'


urlpatterns = [

    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:pk>/<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/delete/<int:pk>/', views.PostDeleteView.as_view(), name='post-delete'),
    path('post/update/<int:pk>/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/create/', views.PostCreateView.as_view(), name='post-create'),
    path('reply/<int:post_pk>/<int:commet_pk>/', views.PostAddReplyView.as_view(), name='add-reply'),
    path('like/<int:pk>/', views.PostLikeView.as_view(), name='post-like'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Relation(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.from_user} -> {self.to_user}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField(default=0)
    bio = models.TextField(null=True, blank=True)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Profile


class UserRegisterForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': 'your password'}))
    password2 = forms.CharField(label='Confirm Password',
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': 'your password again'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('این کاربر قبلا ثبت شده است')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError("کاربری با این نام کاربری وجود دارد")
        return username

    def clean(self):
        cd = super().clean()
        p1 = cd.get('password1')
        p2 = cd.get('password2')
        if p1 and p2 and p1 != p2:
            raise ValidationError('رمز عبور رو یکسان وارد نکردید')


class UserLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}))

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))


class UserProfileForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput())

    class Meta:
        model = Profile
        fields = ['age', 'bio', 'email']

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

from .forms import UserRegisterForm, UserLoginForm, UserProfileForm
from home.models import Post
from .models import Relation


class UserRegisterView(View):
    form_class = UserRegisterForm
    template_name = 'accounts/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.success(request, 'شما در حال حاضر لاگین هستید', extra_tags='info')
            return redirect('home:home')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(
                username=cd['username'], email=cd['email'], password=cd['password1'])
            messages.success(
                request, 'شما با موفقیت ثبت نام شدید', extra_tags='success')
            return redirect('home:home')
        return render(request, self.template_name, {'form': form})


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'کاربر گرامی شما با موفقیت وارد شدید', extra_tags='success')

                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            messages.error(request, 'ایمیل یا رمز عبور شما درست وارد نشده است', extra_tags='warning')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'شما با موفقیت خارج شدید', extra_tags='success')
        return redirect('home:home')


class UserProfileView(LoginRequiredMixin, View):
    form_class = UserProfileForm
    template_name = 'accounts/profile.html'

    # def dispatch(self, request, *args, **kwargs):
    #     user = get_object_or_404(User, pk=kwargs['pk'])
    #     if request.user.id != user.id:
    #         return redirect('home:home')
    #     return super().dispatch(request, *args, **kwargs)

    def get(self, request, pk):
        is_following = False
        user = get_object_or_404(User, pk=pk)
        form = self.form_class(instance=request.user, initial={
            'age': user.profile.age,
            'bio': user.profile.bio,
        })
        posts = user.posts.all()
        relation = Relation.objects.filter(from_user=request.user, to_user=user)

        if relation.exists():
            is_following = True

        return render(request, self.template_name, {
            'user': user,
            'form': form,
            'posts': posts,
            'is_following': is_following
        })

    def post(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        form = self.form_class(request.POST, instance=user)
        if form.is_valid():
            form.save()
            user.profile.age = form.cleaned_data['age']
            user.profile.bio = form.cleaned_data['bio']
            user.profile.save()
            messages.success(request, 'اطلاعات شما با موفقیت تغییر کرد', extra_tags='success')
            return redirect('home:home')
        return render(request, self.template_name, {'form': form})


class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password-reset-done')
    email_template_name = 'accounts/password_reset_email.html'


class UserPasswordResetDone(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password-reset-complete')


class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'


class UserFollowView(LoginRequiredMixin, View):
    def get(self, request, pk):

        user = get_object_or_404(User, id=pk)
        if request.user == user:
            messages.error(request, 'شما نمی‌توانید خودتان را فالو کنید', extra_tags='error')
            return redirect('accounts:user-profile', user.id)

        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            messages.error(request, 'شما در حال حاضر هم این کاربر فالوو می کنید', extra_tags='error')
        else:
            Relation.objects.create(from_user=request.user, to_user=user)
            messages.success(request, 'شما این کاربر رو با موفقیت فالوو کردید', extra_tags='success')
        return redirect('accounts:user-profile', user.id)


class UserUnFollowView(LoginRequiredMixin, View):
    def get(self, request, pk):
        user = get_object_or_404(User, id=pk)
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            relation.delete()
            messages.success(request, 'شما با موفقیت این کاربر رو حذف کردید', extra_tags='success')
        else:
            messages.error(request, 'شما این کاربر رو فالوو ندارید', extra_tags='error')

        return redirect('accounts:user-profile', user.id)

accounts/templates/accounts/login.html
{% extends "_base.html" %}



{% block page_title %}


    Login


{% endblock page_title %}




{% block content %}


    <h2>Login User</h2>


    <form action="" method="post" class="col-md-6" novalidate>

        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" class="btn btn-dark" value='Login'>


    </form>

{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends '_base.html' %}


{% block content %}


    <p>پسورد شما با موفقیت تغییر کرد</p>


{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends '_base.html' %}


{% block content %}

    {% if validlink %}

        <form action="" method="post">


            {% csrf_token %}

            {{ form.as_p }}

            <input type="submit" class="btn btn-dark" value="Change">

        </form>

    {% else %}

        <p>لینک معتبر نیست. لطفا دوباره امتحان کنید.</p>

    {% endif %}





{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends '_base.html' %}


{% block content %}
	
    
    <p>ما برای شما ایمیل ارسال کردیم</p>
    
    
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:

{{ protocol }}://{{ domain }}{% url 'accounts:password-reset-confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends '_base.html' %}



{% block content %}


    <form action="" method="post">

        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" class="btn btn-info" value="Send">


    </form>


{% endblock %}

accounts/templates/accounts/profile.html
{% extends '_base.html' %}

{% block page_title %}
    Profile
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="card shadow-sm">
            <div class="card-body">
                <h2 class="text-center">{{ user.username }}</h2>
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="text-center mt-3">
                        <input type="submit" value="Update" class="btn btn-primary">
                        <a href="{% url 'home:post-create' %}" type="submit" class="btn btn-success">Create Post</a>
                    </div>
                </form>
            </div>
        </div>


        <div class="mt-5">

            {% if request.user.id != user.id and not is_following %}
                <a href="{% url 'accounts:user-follow' user.id %}" class="btn btn-dark">Follow</a>
            {% elif request.user.id != user.id and is_following %}
                <a href="{% url 'accounts:user-unfollow' user.id %}" class="btn btn-danger">UnFollow</a>
            {% endif %}

            <div class="mt-5">
                <div class="row justify-content-center">
                    <div class="col-md-6">
                        <div class="card shadow-sm mb-4">
                            <div class="card-body bg-light">
                                <h5 class="card-title text-center mb-4"><strong>Followers</strong></h5>
                                <ul class="list-group list-group-flush">
                                    {% if user.followers.count > 0 %}
                                        {% for follower in user.followers.all %}
                                            <li class="list-group-item"><a
                                                    href="{% url 'accounts:user-profile' user.profile.id %}"
                                                    class="text-dark">{{ follower.to_user }}</a></li>
                                        {% endfor %}
                                    {% else %}
                                        <li class="list-group-item text-center text-muted">No followers yet.</li>
                                    {% endif %}
                                </ul>
                                <p class="text-center mt-3 text-muted">Total: {{ user.followers.count }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card shadow-sm mb-4">
                            <div class="card-body bg-light">
                                <h5 class="card-title text-center mb-4"><strong>Following</strong></h5>
                                <ul class="list-group list-group-flush">
                                    {% if user.following.count > 0 %}
                                        {% for following in user.following.all %}
                                            <li class="list-group-item"><a
                                                    href="{% url 'accounts:user-profile'  user.profile.id %}"
                                                    class="text-dark">{{ following.from_user }}</a></li>
                                        {% endfor %}
                                    {% else %}
                                        <li class="list-group-item text-center text-muted">Not following anyone yet.
                                        </li>
                                    {% endif %}
                                </ul>
                                <p class="text-center mt-3 text-muted">Total: {{ user.following.count }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>

        <div class="mt-5">
            <h1 class="text-center">List of Posts</h1>
            {% if posts %}
                <div class="list-group mt-3">
                    {% for post in posts %}
                        <div class="list-group-item">
                            <h5 class="mb-1">Slug: {{ post.slug }}</h5>
                            <p class="mb-1">Body: {{ post.body }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p class="text-center">No posts available.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "_base.html" %}



{% block page_title %}


    Register


{% endblock page_title %}




{% block content %}


    <h2>Register User</h2>


    <form action="" method="post" class="col-md-6" novalidate>

        {% csrf_token %}

        {{form.as_p}}

        <input type="submit"  class="btn btn-dark" value='Register'>


    </form>

{% endblock content %}