accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('login/', views.UserLoginView.as_view(), name='user-login'),
    path('logout/', views.UserLogoutView.as_view(), name='user-logout'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='user-profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset-password'),
    path('reset/done/', views.UserPasswordResetDone.as_view(), name='password-reset-done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('confirm/confirm/', views.UserPasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('follow/<int:pk>/', views.UserFollowView.as_view(), name='user-follow'),
    path('unfollow/<int:pk>/', views.UserUnFollowView.as_view(), name='user-unfollow'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'


urlpatterns = [

    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:pk>/<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/delete/<int:pk>/', views.PostDeleteView.as_view(), name='post-delete'),
    path('post/update/<int:pk>/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/create/', views.PostCreateView.as_view(), name='post-create'),
    path('reply/<int:post_pk>/<int:commet_pk>/', views.PostAddReplyView.as_view(), name='add-reply'),
    path('like/<int:pk>/', views.PostLikeView.as_view(), name='post-like'),

]

templates/inc/messages.html
{% if messages %}


    {% for msg in messages  %}
    
    
        <p class="alert alert-{{msg.tags}}">{{msg}}</p>
    
    
    {% endfor %}


{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">StackOverFlow</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "home:home" %}">Home</a>
                </li>


                {% if request.user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:user-logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:user-profile' user.id %}">Profile</a>
                    </li>

                {% else %}


                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:user-register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:user-login' %}">Login</a>
                    </li>

                {% endif %}

            </ul>
        </div>
    </div>
</nav>